group 'federico.amura.flutter_twilio'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.8.20'
    ext.versions = [
            'java'              : JavaVersion.VERSION_1_8,
            'voiceAndroid'      : '6.3.0',
            'audioSwitch'       : '1.1.2',
            'firebaseMessaging' : '23.0.0'
    ]
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }

}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 36
    //ToDoAdded
    if (project.android.hasProperty("namespace")) {
        namespace 'federico.amura.flutter_twilio'
    }
    defaultConfig {
        minSdkVersion 23
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility versions.java
        targetCompatibility versions.java
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    // Split native libraries per ABI to reduce size and fix 16 KB limit
    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a', 'arm64-v8a'
            universalApk false
        }
    }

    // Optional: pick first if duplicate .so files exist
    packagingOptions {
        jniLibs {
            pickFirst '**/*.so'
        }
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:26.0.0')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.twilio:audioswitch:${versions.audioSwitch}"
    implementation "com.twilio:voice-android:${versions.voiceAndroid}"
    implementation "com.google.firebase:firebase-messaging:${versions.firebaseMessaging}"
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
    implementation 'androidx.work:work-runtime-ktx:2.8.1'
}
