group 'federico.amura.flutter_twilio'
version '1.0-SNAPSHOT'

buildscript {
    ext {
        kotlinVersion           = "1.9.10"
        agpVersion              = "8.5.2"
        twilioVoiceVersion      = "6.9.0"
        audioSwitch             = '1.1.2'
    }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:${agpVersion}"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    compileSdk = 36

    if (project.android.hasProperty("namespace")) {
        namespace = 'federico.amura.flutter_twilio'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 24
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:${kotlinVersion}"))
    implementation(platform("com.google.firebase:firebase-bom:33.10.0"))
    implementation("com.twilio:voice-android:${twilioVoiceVersion}")
    implementation "com.twilio:audioswitch:${audioSwitch}"
    implementation("com.google.firebase:firebase-messaging-ktx:24.1.0")
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.lifecycle:lifecycle-process:2.8.7'
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
    implementation 'androidx.work:work-runtime-ktx:2.8.1'
}
